### ISSUE TITLE
querySelectorAll vs. getElementsByTagName

### ISSUE THREAD

**Issue by pwFoo** [anywhichway/tlx#10]
`querySelectorAll()´ is used to just get elements by tag name?
https://github.com/anywhichway/tlx/blob/8ead7e058a9472cec9abd08b13f1ca7cf7460916/index.js#L433

Maybe it could be better for performence to use `getElementsByTagName` (difference: faster, but node list is dynamic and not static, it reacts to changes).
```
const inputs = slice(el.getElementsByTagName("input"));
```

That example is more complex because of two selectors, but getElementsByTagName is still faster.
https://jsperf.com/queryselectorall-vs-getelementsbytagname/40

**Comment by anywhichway** [comment]
@pwFoo This was a good find. However, when looking at the code we also realized we were not protecting `textarea`. In the next build it will be protected. Conveniently `querySelectorAll` supports comma separation, i.e. `el.querySelectorAll("input, textarea")`. In this case we are going to opt for smaller and simpler code rather than make two queries and merge the results which will require two conversions to arrays and a concat, or something similar.

**Comment by pwFoo** [comment]
Ok, with added textarea it is simpler with querySelectorAll(), but also with two calls getElementsByTagName() is much faster. But querySelectorAll should be fine for now. If there would be performance issues, that could be a point to optimize.

So close is fine for now. 👍
